<a href="https://colab.research.google.com/github/Endalebob/Deep-Learning-Lab/blob/main/DL_Lab_3_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
'''
inp-4
lay-3
node-18
outp-3
h-act-relu-sigmoid
o-act-softmax
loss=c.c.el
accuracy
'''

In [99]:
class DenseLayer:
  def __init__(self,n_features,n_nodes):
    self.weights = torch.rand((n_features,n_nodes))
    self.bias = torch.zeros((1,n_nodes))
  def forward(self,inputs):
    self.output = torch.matmul(inputs,self.weights)+self.bias

In [100]:
inputs = torch.rand((5,4))
inputs -= 0.3
inputs

tensor([[ 0.5850,  0.5996,  0.6602,  0.5218],
        [ 0.4616,  0.4963,  0.4278,  0.6904],
        [ 0.1638,  0.5229,  0.3972,  0.4802],
        [-0.1106,  0.4565, -0.1625,  0.1749],
        [-0.1141, -0.1488,  0.1672,  0.3371]])

In [101]:
class ActivationReLU(torch.nn.Module):
    def forward(self, inputs):
        """
        ReLU function:
        ReLU(x) = max(0, x)

        Args:
            inputs (torch.Tensor): Input tensor.
        """
        # Step 1: Compute the element-wise maximum with 0
        relu_output = torch.max(torch.tensor(0), inputs)

        return relu_output


In [102]:
layer1 = DenseLayer(len(inputs[0]),18)
layer1.forward(inputs)
relu = ActivationReLU()
layer1_output = relu.forward(layer1.output)
layer1_output

tensor([[0.7490, 1.0608, 1.5070, 1.4546, 1.3501, 0.7518, 0.7841, 1.5346, 1.2480,
         1.1036, 1.1595, 0.8110, 1.3889, 0.9876, 1.2407, 1.1040, 1.6128, 1.3730],
        [0.6254, 1.0325, 1.2613, 1.3298, 1.2897, 0.6466, 0.7021, 1.3412, 1.1072,
         0.9177, 1.1232, 0.6661, 1.0798, 0.7708, 1.0064, 0.8681, 1.4669, 1.1118],
        [0.4802, 0.6809, 1.0388, 0.9490, 0.9433, 0.5534, 0.5696, 1.0924, 0.9939,
         0.7324, 0.8863, 0.6057, 0.8792, 0.7553, 0.7682, 0.6005, 0.9862, 0.8624],
        [0.0000, 0.2163, 0.3260, 0.1595, 0.1560, 0.3125, 0.3000, 0.2868, 0.4279,
         0.2131, 0.1998, 0.2626, 0.1081, 0.3672, 0.2401, 0.0350, 0.0785, 0.1752],
        [0.1707, 0.0959, 0.0715, 0.2337, 0.3465, 0.0000, 0.0000, 0.2162, 0.1472,
         0.0310, 0.3579, 0.0096, 0.0843, 0.0000, 0.0000, 0.0000, 0.2546, 0.0349]])

In [103]:
class ActivationSigmoid(torch.nn.Module):
    def forward(self, inputs):
        """
        Sigmoid function:
        Sigmoid(x) = 1 / (1 + exp(-x))

        Args:
            inputs (torch.Tensor): Input tensor.
        """
        # Step 1: Compute the element-wise exponentiation
        exp_inputs = torch.exp(-inputs)

        # Step 2: Compute the element-wise reciprocal (1 / (1 + exp(-x)))
        sigmoid_output = 1 / (1 + exp_inputs)

        return sigmoid_output


In [104]:
layer2 = DenseLayer(len(layer1_output[0]),18)
layer2.forward(layer1_output)
sigmoid = ActivationSigmoid()
layer2_output = sigmoid.forward(layer2.output)
layer2_output

tensor([[0.9999, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 0.9999, 1.0000,
         0.9998, 0.9999, 1.0000, 1.0000, 1.0000, 0.9999, 1.0000, 1.0000, 0.9999],
        [0.9998, 0.9998, 0.9999, 1.0000, 0.9999, 0.9999, 0.9997, 0.9998, 0.9998,
         0.9993, 0.9998, 0.9999, 1.0000, 0.9999, 0.9996, 1.0000, 0.9998, 0.9997],
        [0.9984, 0.9989, 0.9995, 0.9996, 0.9992, 0.9995, 0.9982, 0.9988, 0.9989,
         0.9968, 0.9986, 0.9994, 0.9996, 0.9993, 0.9976, 0.9997, 0.9988, 0.9983],
        [0.8324, 0.8766, 0.8922, 0.8769, 0.8823, 0.8893, 0.8185, 0.8611, 0.8838,
         0.8095, 0.8488, 0.8861, 0.8869, 0.8778, 0.8389, 0.8819, 0.8592, 0.8366],
        [0.7525, 0.6815, 0.7697, 0.7914, 0.7369, 0.7873, 0.7330, 0.7088, 0.7443,
         0.6995, 0.6899, 0.7509, 0.7357, 0.7556, 0.6909, 0.7901, 0.7171, 0.7100]])

In [105]:
class ActivationSoftmax(torch.nn.Module):
    def forward(self, inputs):
        """
        Softmax function:
        Softmax(x)_i = exp(x_i) / sum(exp(x))

        Args:
            inputs (torch.Tensor): Input tensor of shape (batch_size, num_classes).
        """
        # Step 1: Compute the maximum value along axis 1 (columns)
        max_inputs, _ = torch.max(inputs, dim=1, keepdim=True)

        # Step 2: Subtract the maximum to prevent overflow
        inputs -= max_inputs

        # Step 3: Compute element-wise exponentiation
        exp_inputs = torch.exp(inputs)

        # Step 4: Compute the sum along axis 1 (columns) to get the denominator
        sum_exp_inputs = torch.sum(exp_inputs, dim=1, keepdim=True)

        # Step 5: Element-wise division of exp_inputs by the sum_exp_inputs
        softmax_output = exp_inputs / sum_exp_inputs

        return softmax_output


In [106]:
layer3 = DenseLayer(len(layer2.output[0]),18)
layer3.forward(layer2.output)
relu = ActivationReLU()
layer3_output = relu.forward(layer3.output)
layer3_output

tensor([[ 92.9062,  91.3023,  81.1489,  72.0489,  70.7286,  80.8314,  87.6328,
          98.5299,  94.6837,  99.7296,  80.1876,  69.0602,  97.4812,  93.5821,
          94.6993,  95.8192, 108.1552, 102.9164],
        [ 80.5697,  79.1961,  70.2199,  62.4947,  61.3633,  70.2345,  75.8674,
          85.3675,  82.0248,  86.4670,  69.5151,  59.7327,  84.3829,  81.2252,
          82.1179,  83.2936,  93.7694,  89.3328],
        [ 63.0180,  61.9796,  54.9211,  48.9371,  47.8667,  54.8944,  59.4667,
          66.9188,  64.1331,  67.6857,  54.5298,  46.8707,  66.1833,  63.3995,
          64.2565,  65.0245,  73.3506,  69.9697],
        [ 16.7309,  16.5925,  14.5185,  12.8387,  12.5281,  14.4617,  15.8468,
          18.0508,  16.9563,  18.0708,  14.8696,  12.5817,  17.7149,  16.7402,
          17.0683,  17.3756,  19.6313,  18.5823],
        [  9.4021,   9.1546,   8.0120,   7.5401,   7.1745,   8.4483,   8.7398,
           9.7512,   9.4368,   9.9994,   7.8442,   6.7883,   9.6306,   9.4957,
          

In [107]:
output = DenseLayer(len(layer3.output[0]),3)
output.forward(layer3.output)
softmax = ActivationSoftmax()

final_output = softmax.forward(output.output)
final_output

tensor([[0.0000e+00, 1.2303e-24, 1.0000e+00],
        [5.4230e-43, 1.6536e-21, 1.0000e+00],
        [9.0897e-34, 6.4474e-17, 1.0000e+00],
        [1.2733e-09, 5.7412e-05, 9.9994e-01],
        [1.6194e-05, 3.4431e-03, 9.9654e-01]])

In [109]:
torch.argmax(final_output,dim=1)

tensor([2, 2, 2, 2, 2])

In [110]:
class LossCategoricalCrossEntropy:
    def forward(self, y_pred, y_true):
        """
        Categorical Cross-Entropy Loss function for classification tasks.

        Args:
            y_pred (torch.Tensor): Predicted class probabilities (e.g., output from softmax).
            y_true (torch.Tensor): True class labels as one-hot encoded vectors.

        Returns:
            torch.Tensor: Categorical Cross-Entropy Loss.
        """
        # Calculate the negative log likelihood of the true class labels
        loss = -torch.sum(y_true * torch.log(y_pred + 1e-15)) / y_true.size(0)

        return loss


In [112]:
import torch
import torch.nn as nn

# Define your true class labels in one-hot encoded format
true_labels = torch.tensor([[0, 0, 1],  # Row 0: Correct prediction is class 2
                            [0, 1, 0],  # Row 1: Correct prediction is class 1
                            [0, 0, 1],  # Row 2: Correct prediction is class 2
                            [1, 0, 0],
                            [0, 0, 1]]) # Row 4: Correct prediction is class 0

# Example of predicted class probabilities (output from your final layer)
predicted_probs = final_output

# Create the LossCategoricalCrossEntropy module
loss_fn = LossCategoricalCrossEntropy()

# Calculate the loss
loss = loss_fn.forward(predicted_probs, true_labels)

print("Categorical Cross-Entropy Loss:", loss.item())


Categorical Cross-Entropy Loss: 11.004776000976562


In [113]:
class Accuracy(nn.Module):
    def forward(self, y_pred, y_true):
        """
        Calculate the classification accuracy.

        Args:
            y_pred (torch.Tensor): Predicted class probabilities (e.g., output from softmax).
            y_true (torch.Tensor): True class labels as one-hot encoded vectors.

        Returns:
            torch.Tensor: Classification accuracy.
        """
        # Get the predicted class labels by finding the index of the maximum probability
        pred_labels = torch.argmax(y_pred, dim=1)

        # Get the true class labels by finding the index of the one-hot encoded vectors
        true_labels = torch.argmax(y_true, dim=1)

        # Compare predicted labels with true labels and calculate accuracy
        correct_predictions = torch.eq(pred_labels, true_labels).float()
        accuracy = torch.mean(correct_predictions)

        return accuracy


In [114]:
# Calculate the accuracy
accuracy_class = Accuracy()
accuracy = accuracy_class.forward(predicted_probs, true_labels)

print("Accuracy:", accuracy.item())

Accuracy: 0.6000000238418579
